### ISSUE TITLE
Robot API: Animations / Images on Belly Screen

### ISSUE THREAD

**Issue by patricialvesoliveira** [mayacakmak/emarsoftware#12]
Can we have the option to display animations (e.g., a timer) or images (e.g., a heart) on the Belly Screen? Tanya and I designed the Yes / No micro-intervention considering this possibility, so it would be great if we have it!

**Comment by kaimihata** [comment]
Added this functionality to the backend, but not to the frontend yet, so images can be added via the database but there is no UI in the front end for this feature yet.
